### ISSUE TITLE
How to use it with processing. ?

### ISSUE THREAD

**Issue by nj-AllAboutCode** [kim-marcel/basic_neural_network#3]
How to use it with Processing.
in readme it is to download the jar file.
where is the jar-file ??

**Comment by Trolley33** [comment]
[Here.](https://github.com/kim-marcel/basic_neural_network/releases/download/v0.4/basic_neural_network-v0.4.jar)

**Comment by kim-marcel** [comment]
@nj-AllAboutCode The readme has a Download section where the newest version can be downloaded. In Addition, all releases (past and most recent) can be found in the [release tab](https://github.com/kim-marcel/basic_neural_network/releases) of the repository.
